name: Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Set version for tag or branch
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=dev-main" >> $GITHUB_ENV
          fi

      - name: Build DEB
        uses: ./.github/actions/deb-build
        with:
          package-name: smee
          package-root: src
          maintainer: ${{ github.repository_owner }}
          version: ${{ env.VERSION }}
          desc: ${{ vars.README_DESCRIPTION }}
          homepage: ${{ github.server_url }}/${{ github.repository }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-force-creation: false
          repository-sub-directory: apt

      - name: Deploy to Github Pages
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated APT repository"
          git push origin HEAD:gh-pages

  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Set version for tag or branch
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=dev-main" >> $GITHUB_ENV
          fi

      - name: Build RPM
        uses: ./.github/actions/rpm-build
        with:
          package-name: smee
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ inputs.token }}
          publish_dir: rpm-repo/
          destination_dir: ${{ inputs.repository-sub-directory || 'rpm' }}
