name: Build and Deploy RPM

on:
  push:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Build DEB
        uses: ./.github/actions/deb-build
        with:
          package-name: smee
          package-root: src
          maintainer: ${{ github.repository_owner }}
          version: "0.0.1"
          desc: ${{ vars.README_DESCRIPTION }}
          homepage: ${{ github.server_url }}/${{ github.repository }}
          # gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          # gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Build RPM
        uses: ./.github/actions/rpm-build
        with:
          package-name: smee
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
